name: Snake Animation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build snake animation
      run: npm run build
    - name: Upload snake animation
      uses: actions/upload-artifact@v2
      with:
        name: snake-animation
        path: ./dist
